"""crear tabla predictions2

Revision ID: 267ff40c9f71
Revises: 83b2b396191e
Create Date: 2025-05-19 10:26:17.146772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '267ff40c9f71'
down_revision: Union[str, None] = '83b2b396191e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'fecha',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'fecha',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
